name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v6

    - name: install toolchain
      run: | 
        mkdir -p ~/esp;
        cd ~/esp
        git clone -b v5.5.1 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf  
        ./install.sh esp32p4
        source export.sh
 
    - name: set target chip
      run: ~/idf.py set-target esp32p4


 
        
